name: Build iOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: 📦 Checkout repo
        uses: actions/checkout@v3

      - name: 🧰 Download Godot 4.3
        run: |
          curl -L https://github.com/godotengine/godot-builds/releases/download/4.3-stable/Godot_v4.3-stable_macos.universal.zip -o godot.zip
          unzip godot.zip -d godot
          sudo mv godot/Godot.app /Applications/Godot.app
          sudo ln -s /Applications/Godot.app/Contents/MacOS/Godot /usr/local/bin/godot

      - name: 📦 Download iOS Export Templates
        run: |
          mkdir -p ~/Library/Application\ Support/Godot/export_templates/4.3.stable
         curl -L https://downloads.tuxfamily.org/godotengine/4.3/rc2/export_templates/GodotExportTemplates_v4.3-rc2_iOS.zip -o ~/Library/Application\ Support/Godot/export_templates/4.3.stable/ios.zip
      - name: 🏗 Create build folder
        run: mkdir -p build

      - name: 🚀 Export iOS project
        run: |
          godot --headless --export-release "Noriko" build/noriko-cooking.xcodeproj
        env:
          DISPLAY: :99.0

      - name: 📦 Archive .ipa
        run: |
          cd build
          xcodebuild -project noriko-cooking.xcodeproj -scheme "noriko-cooking" -configuration Release -archivePath noriko-cooking.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: 📦 Package IPA
        run: |
          cd build
          mkdir -p Payload
          cp -r noriko-cooking.xcarchive/Products/Applications/noriko-cooking.app Payload/
          zip -r noriko-cooking.ipa Payload

      - name: 📤 Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: NorikoIPA
          path: build/noriko-cooking.ipa
